server:
  port: 1688
spring:

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    name: datasource

    url: jdbc:mysql://localhost:3306/bilibili?useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: user
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
    sleuth:
      sampler:
        probability: 1
  application:
    name: chat
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        register-enabled: true
module-name: chat